#!/usr/bin/env node
/**
 * CLI init wizard for next-api-layer
 * Usage: npx next-api-layer init
 * 
 * Zero dependencies - uses native Node.js readline
 */

import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import fs from 'node:fs';
import path from 'node:path';

interface InitAnswers {
  backend: string;
  apiBaseUrl: string;
  useI18n: boolean;
  defaultLocale?: string;
  useGuestToken: boolean;
  protectedRoutes: string;
  authRoutes: string;
}

const BACKEND_PRESETS: Record<string, { methodSpoofing: boolean; description: string }> = {
  laravel: { methodSpoofing: true, description: 'Laravel (PHP)' },
  rails: { methodSpoofing: true, description: 'Ruby on Rails' },
  django: { methodSpoofing: false, description: 'Django (Python)' },
  dotnet: { methodSpoofing: false, description: '.NET Core / ASP.NET' },
  express: { methodSpoofing: false, description: 'Express.js (Node)' },
  go: { methodSpoofing: false, description: 'Go (Gin, Echo, etc.)' },
  other: { methodSpoofing: false, description: 'Other' },
};

const BACKEND_KEYS = Object.keys(BACKEND_PRESETS);

async function main() {
  const rl = readline.createInterface({ input, output });
  
  console.log('\n\x1b[36m next-api-layer setup\x1b[0m\n');

  try {
    // Backend selection
    console.log('Backend framework:');
    BACKEND_KEYS.forEach((key, i) => {
      console.log(`  ${i + 1}) ${BACKEND_PRESETS[key].description}`);
    });
    
    const backendChoice = await rl.question('\nSelect (1-7): ');
    const backendIndex = parseInt(backendChoice, 10) - 1;
    
    if (isNaN(backendIndex) || backendIndex < 0 || backendIndex >= BACKEND_KEYS.length) {
      console.log('\n\x1b[31mInvalid selection. Setup cancelled.\x1b[0m\n');
      rl.close();
      process.exit(1);
    }
    
    const backend = BACKEND_KEYS[backendIndex];
    const preset = BACKEND_PRESETS[backend];

    // API Base URL
    const apiBaseUrl = await rl.question('\nAPI base URL (leave empty to use env): ');

    // i18n
    const useI18nInput = await rl.question('\nUse i18n (next-intl)? (y/N): ');
    const useI18n = useI18nInput.toLowerCase() === 'y' || useI18nInput.toLowerCase() === 'yes';
    
    let defaultLocale: string | undefined;
    if (useI18n) {
      defaultLocale = await rl.question('Default locale (en): ') || 'en';
    }

    // Guest token
    const useGuestTokenInput = await rl.question('\nUse guest token for unauthenticated users? (y/N): ');
    const useGuestToken = useGuestTokenInput.toLowerCase() === 'y' || useGuestTokenInput.toLowerCase() === 'yes';

    // Protected routes
    const protectedRoutes = await rl.question('\nProtected routes (comma-separated, e.g. /dashboard,/profile): ');
    
    // Auth routes
    const authRoutes = await rl.question('Auth routes - redirect if logged in (e.g. /login,/register): ');

    const answers: InitAnswers = {
      backend,
      apiBaseUrl: apiBaseUrl.trim(),
      useI18n,
      defaultLocale,
      useGuestToken,
      protectedRoutes: protectedRoutes.trim(),
      authRoutes: authRoutes.trim(),
    };

    const config = generateConfig(answers, preset);

    // Determine output path
    const outputDir = findConfigDir();
    const outputPath = path.join(outputDir, 'auth.config.ts');

    // Check if file exists
    if (fs.existsSync(outputPath)) {
      const overwriteInput = await rl.question(`\n${outputPath} already exists. Overwrite? (y/N): `);
      const overwrite = overwriteInput.toLowerCase() === 'y' || overwriteInput.toLowerCase() === 'yes';

      if (!overwrite) {
        console.log('\n\x1b[31mSetup cancelled.\x1b[0m\n');
        rl.close();
        process.exit(1);
      }
    }

    // Ensure directory exists
    fs.mkdirSync(outputDir, { recursive: true });

    // Write config file
    fs.writeFileSync(outputPath, config, 'utf-8');

    console.log(`\n\x1b[32mCreated ${outputPath}\x1b[0m\n`);
    console.log('Next steps:');
    console.log('  1. Review and update the config file');
    console.log('  2. Create your proxy route: app/api/[...path]/route.ts');
    console.log('  3. Import { authProxy, api } from your config\n');

    if (preset.methodSpoofing) {
      console.log(`\x1b[33mMethod spoofing enabled for ${backend} (PUT/PATCH -> POST + _method)\x1b[0m\n`);
    }

    rl.close();
  } catch (err) {
    rl.close();
    // User pressed Ctrl+C
    if ((err as NodeJS.ErrnoException).code === 'ERR_USE_AFTER_CLOSE') {
      console.log('\n\x1b[31mSetup cancelled.\x1b[0m\n');
      process.exit(1);
    }
    throw err;
  }
}

function generateConfig(answers: InitAnswers, preset: { methodSpoofing: boolean }): string {
  const apiUrlValue = answers.apiBaseUrl 
    ? `'${answers.apiBaseUrl}'` 
    : `process.env.API_BASE_URL || 'http://localhost:8000/api'`;

  const lines: string[] = [
    `/**`,
    ` * next-api-layer configuration`,
    ` * Generated by: npx next-api-layer init`,
    ` */`,
    ``,
    `import { createAuthProxy, createApiClient } from 'next-api-layer';`,
    ``,
    `// ==================== Auth Proxy ====================`,
    ``,
    `export const authProxy = createAuthProxy({`,
    `  apiBaseUrl: ${apiUrlValue},`,
    ``,
    `  cookies: {`,
    `    user: 'auth_token',`,
    `    guest: 'guest_token',`,
    `  },`,
    ``,
    `  endpoints: {`,
    `    validate: 'auth/me',`,
    `    refresh: 'auth/refresh',`,
    `    guest: 'auth/guest',`,
    `  },`,
  ];

  // Guest token
  if (answers.useGuestToken) {
    lines.push(``,
      `  guestToken: {`,
      `    enabled: true,`,
      `    // credentials: { username: 'guest', password: 'guest' },`,
      `  },`
    );
  } else {
    lines.push(``,
      `  guestToken: {`,
      `    enabled: false,`,
      `  },`
    );
  }

  // i18n
  if (answers.useI18n) {
    lines.push(``,
      `  i18n: {`,
      `    enabled: true,`,
      `    defaultLocale: '${answers.defaultLocale || 'en'}',`,
      `  },`
    );
  }

  // Access control
  const protectedArr = answers.protectedRoutes 
    ? answers.protectedRoutes.split(',').map(r => r.trim()).filter(Boolean)
    : [];
  const authArr = answers.authRoutes
    ? answers.authRoutes.split(',').map(r => r.trim()).filter(Boolean)
    : [];
  
  if (protectedArr.length > 0 || authArr.length > 0) {
    lines.push(``,
      `  access: {`
    );
    if (protectedArr.length > 0) {
      lines.push(`    protectedRoutes: [${protectedArr.map(r => `'${r}'`).join(', ')}],`);
    }
    if (authArr.length > 0) {
      lines.push(`    authRoutes: [${authArr.map(r => `'${r}'`).join(', ')}],`);
    }
    lines.push(`  },`);
  }

  lines.push(`});`, ``);

  // API Client
  lines.push(
    `// ==================== API Client ====================`,
    ``,
    `export const api = createApiClient({`,
    `  apiBaseUrl: ${apiUrlValue},`,
    ``,
    `  cookies: {`,
    `    user: 'auth_token',`,
    `    guest: 'guest_token',`,
    `  },`
  );

  // Method spoofing
  if (preset.methodSpoofing) {
    lines.push(``,
      `  methodSpoofing: true, // ${answers.backend === 'laravel' ? 'Laravel' : 'Rails'} PUT/PATCH support`);
  }

  // Sanitization (always on by default)
  lines.push(
    ``,
    `  sanitization: {`,
    `    enabled: true,`,
    `    mode: 'escape', // 'escape' | 'strip' | 'allowList'`,
    `  },`
  );

  // i18n for API client
  if (answers.useI18n) {
    lines.push(
      ``,
      `  i18n: {`,
      `    enabled: true,`,
      `    paramName: 'lang',`,
      `  },`
    );
  }

  lines.push(`});`, ``);

  // v0.2.0+ Advanced features as comments
  lines.push(
    `// ==================== Advanced Options ====================`,
    `// Uncomment and add these to createApiClient config:`,
    `//`,
    `// retry: { enabled: true, maxAttempts: 3, backoff: 'exponential' },`,
    `// debug: { enabled: process.env.NODE_ENV === 'development' },`,
    `// timeout: 30000,`,
    `//`,
    `// Add these to createAuthProxy config:`,
    `// csrf: { enabled: true },`,
    `// rateLimit: { enabled: true, maxRequests: 100, windowMs: 60000 },`,
    ``
  );

  // Export types
  lines.push(
    `// Re-export for convenience`,
    `export type { ApiResponse } from 'next-api-layer';`,
    ``
  );

  return lines.join('\n');
}

function findConfigDir(): string {
  // Look for common directories
  const candidates = [
    'lib/auth',
    'src/lib/auth',
    'lib',
    'src/lib',
    'config',
    'src/config',
  ];

  for (const dir of candidates) {
    if (fs.existsSync(dir)) {
      return dir;
    }
  }

  // Default to lib/auth
  return 'lib/auth';
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
