#!/usr/bin/env node
/**
 * CLI init wizard for next-api-layer
 * Usage: npx next-api-layer init
 */

import prompts from 'prompts';
import fs from 'fs';
import path from 'path';

interface InitAnswers {
  backend: 'laravel' | 'rails' | 'django' | 'dotnet' | 'express' | 'go' | 'other';
  apiBaseUrl: string;
  useI18n: boolean;
  defaultLocale?: string;
  useGuestToken: boolean;
}

const BACKEND_PRESETS: Record<string, { methodSpoofing: boolean; description: string }> = {
  laravel: { methodSpoofing: true, description: 'Laravel (PHP)' },
  rails: { methodSpoofing: true, description: 'Ruby on Rails' },
  django: { methodSpoofing: false, description: 'Django (Python)' },
  dotnet: { methodSpoofing: false, description: '.NET Core / ASP.NET' },
  express: { methodSpoofing: false, description: 'Express.js (Node)' },
  go: { methodSpoofing: false, description: 'Go (Gin, Echo, etc.)' },
  other: { methodSpoofing: false, description: 'Other' },
};

async function main() {
  console.log('\n🔐 next-api-layer setup\n');

  const answers = await prompts([
    {
      type: 'select',
      name: 'backend',
      message: 'Backend framework?',
      choices: Object.entries(BACKEND_PRESETS).map(([value, { description }]) => ({
        title: description,
        value,
      })),
    },
    {
      type: 'text',
      name: 'apiBaseUrl',
      message: 'API base URL? (Enter to skip)',
      initial: '',
      hint: 'e.g. http://localhost:8000/api',
    },
    {
      type: 'confirm',
      name: 'useI18n',
      message: 'Use i18n (next-intl)?',
      initial: false,
    },
    {
      type: (prev) => prev ? 'text' : null,
      name: 'defaultLocale',
      message: 'Default locale?',
      initial: 'en',
    },
    {
      type: 'confirm',
      name: 'useGuestToken',
      message: 'Use guest token for unauthenticated users?',
      initial: false,
    },
  ]);

  // User cancelled
  if (!answers.backend) {
    console.log('\n❌ Setup cancelled.\n');
    process.exit(1);
  }

  const preset = BACKEND_PRESETS[answers.backend];
  const config = generateConfig(answers, preset);

  // Determine output path
  const outputDir = findConfigDir();
  const outputPath = path.join(outputDir, 'auth.config.ts');

  // Check if file exists
  if (fs.existsSync(outputPath)) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: `${outputPath} already exists. Overwrite?`,
      initial: false,
    });

    if (!overwrite) {
      console.log('\n❌ Setup cancelled.\n');
      process.exit(1);
    }
  }

  // Ensure directory exists
  fs.mkdirSync(outputDir, { recursive: true });

  // Write config file
  fs.writeFileSync(outputPath, config, 'utf-8');

  console.log(`\n✅ Created ${outputPath}\n`);
  console.log('Next steps:');
  console.log('  1. Review and update the config file');
  console.log('  2. Create your proxy route: app/api/[...path]/route.ts');
  console.log('  3. Import { authProxy, api } from your config\n');

  if (preset.methodSpoofing) {
    console.log(`💡 Method spoofing enabled for ${answers.backend} (PUT/PATCH → POST + _method)\n`);
  }
}

function generateConfig(answers: InitAnswers, preset: { methodSpoofing: boolean }): string {
  const apiUrlValue = answers.apiBaseUrl 
    ? `'${answers.apiBaseUrl}'` 
    : `process.env.API_BASE_URL || 'http://localhost:8000/api'`;

  const lines: string[] = [
    `/**`,
    ` * next-api-layer configuration`,
    ` * Generated by: npx next-api-layer init`,
    ` */`,
    ``,
    `import { createAuthProxy, createApiClient } from 'next-api-layer';`,
    ``,
    `// ==================== Auth Proxy ====================`,
    ``,
    `export const authProxy = createAuthProxy({`,
    `  apiBaseUrl: ${apiUrlValue},`,
    ``,
    `  cookies: {`,
    `    user: 'auth_token',`,
    `    guest: 'guest_token',`,
    `  },`,
    ``,
    `  endpoints: {`,
    `    validate: 'auth/me',`,
    `    refresh: 'auth/refresh',`,
    `    guest: 'auth/guest',`,
    `  },`,
  ];

  // Guest token
  if (answers.useGuestToken) {
    lines.push(``,
      `  guestToken: {`,
      `    enabled: true,`,
      `    // credentials: { username: 'guest', password: 'guest' },`,
      `  },`
    );
  } else {
    lines.push(``,
      `  guestToken: {`,
      `    enabled: false,`,
      `  },`
    );
  }

  // i18n
  if (answers.useI18n) {
    lines.push(``,
      `  i18n: {`,
      `    enabled: true,`,
      `    defaultLocale: '${answers.defaultLocale || 'en'}',`,
      `  },`
    );
  }

  lines.push(`});`, ``);

  // API Client
  lines.push(
    `// ==================== API Client ====================`,
    ``,
    `export const api = createApiClient({`
  );

  // Method spoofing
  if (preset.methodSpoofing) {
    lines.push(`  methodSpoofing: true, // ${answers.backend === 'laravel' ? 'Laravel' : 'Rails'} PUT/PATCH support`);
  }

  // Sanitization (always on by default)
  lines.push(
    ``,
    `  sanitization: {`,
    `    enabled: true,`,
    `    mode: 'escape', // 'escape' | 'strip' | 'allowList'`,
    `  },`
  );

  // i18n for API client
  if (answers.useI18n) {
    lines.push(
      ``,
      `  i18n: {`,
      `    enabled: true,`,
      `    paramName: 'lang',`,
      `  },`
    );
  }

  lines.push(`});`, ``);

  // Export types
  lines.push(
    `// Re-export for convenience`,
    `export type { ApiResponse } from 'next-api-layer/api';`,
    ``
  );

  return lines.join('\n');
}

function findConfigDir(): string {
  // Look for common directories
  const candidates = [
    'lib/auth',
    'src/lib/auth',
    'lib',
    'src/lib',
    'config',
    'src/config',
  ];

  for (const dir of candidates) {
    if (fs.existsSync(dir)) {
      return dir;
    }
  }

  // Default to lib/auth
  return 'lib/auth';
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
